#!/usr/bin/env python3
"""Gzip the phone page into a C header so the sketch can serve it from flash.

Run after every change to index.html:
    python3 crowdcourse/embed_html.py
"""
import gzip
import pathlib

here = pathlib.Path(__file__).resolve().parent
src = here / "index.html"
dst = here / "index_html.h"

raw = src.read_bytes()
gz = gzip.compress(raw, compresslevel=9, mtime=0)

lines = []
for i in range(0, len(gz), 20):
    lines.append("  " + ", ".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")

header = (
    "// Generated by embed_html.py from index.html. Do not edit by hand.\n"
    "#pragma once\n"
    "#include <Arduino.h>\n\n"
    f"const size_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
    "const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n" + "\n".join(lines) + "\n};\n"
)
dst.write_text(header)
print(f"{src.name}: {len(raw)} bytes -> {len(gz)} bytes gzipped -> {dst.name}")
