#!/usr/bin/env python3
"""Gzip index.html into a C header so the sketch can serve it from flash.

Writes index_html.h into every sketch folder under firmware/. Run after every change to index.html:
    python3 firmware/embed_html.py
"""
import gzip
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = root / "index.html"
sketches = sorted(p.parent for p in (root / "firmware").glob("*/*.ino"))

raw = src.read_bytes()
gz = gzip.compress(raw, compresslevel=9, mtime=0)

lines = []
for i in range(0, len(gz), 20):
    lines.append("  " + ", ".join(f"0x{b:02x}" for b in gz[i:i + 20]) + ",")

header = (
    "// Generated by firmware/embed_html.py from index.html. Do not edit by hand.\n"
    "#pragma once\n"
    "#include <Arduino.h>\n\n"
    f"const size_t INDEX_HTML_GZ_LEN = {len(gz)};\n"
    "const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n" + "\n".join(lines) + "\n};\n"
)
for sketch in sketches:
    dst = sketch / "index_html.h"
    dst.write_text(header)
    print(f"{src.name}: {len(raw)} bytes -> {len(gz)} bytes gzipped -> {dst.relative_to(root)}")
